"""add_plaid_fields

Revision ID: cc5c432fa36c
Revises: 1ca1ba00a83b
Create Date: 2026-05-22 17:08:42.963028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc5c432fa36c'
down_revision: Union[str, None] = '1ca1ba00a83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_cursor', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('plaid_transaction_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['plaid_transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'plaid_transaction_id')
    op.drop_column('accounts', 'last_cursor')
    # ### end Alembic commands ###
